// File generated by FlutterFire CLI.
//
// Location note: the FlutterFire CLI writes to lib/firebase_options.dart by
// default. This project keeps it alongside the other notification code, so
// re-run configure with the matching --out flag to refresh it:
//
//   flutterfire configure --project=tech-runbit-denta \
//       --out=lib/core/services/notifications/firebase_options.dart
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQjsxHRMueso0t6OYir68GCJdYLGbVPY',
    appId: '1:971977021027:web:d3e578784011292ce30a56',
    messagingSenderId: '971977021027',
    projectId: 'tech-runbit-denta',
    authDomain: 'tech-runbit-denta.firebaseapp.com',
    storageBucket: 'tech-runbit-denta.firebasestorage.app',
    measurementId: 'G-ZYVX1NCHQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6IyewWCDWjG0oeqKJS9fCiSsYcWlo4MU',
    appId: '1:971977021027:android:311de2da8d046b64e30a56',
    messagingSenderId: '971977021027',
    projectId: 'tech-runbit-denta',
    storageBucket: 'tech-runbit-denta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeqdHmNve7t75qO4mF6C-rq0S4C9hI1Fw',
    appId: '1:971977021027:ios:0f54d386342860fde30a56',
    messagingSenderId: '971977021027',
    projectId: 'tech-runbit-denta',
    storageBucket: 'tech-runbit-denta.firebasestorage.app',
    iosBundleId: 'com.example.dentalClinicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeqdHmNve7t75qO4mF6C-rq0S4C9hI1Fw',
    appId: '1:971977021027:ios:0f54d386342860fde30a56',
    messagingSenderId: '971977021027',
    projectId: 'tech-runbit-denta',
    storageBucket: 'tech-runbit-denta.firebasestorage.app',
    iosBundleId: 'com.example.dentalClinicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXQjsxHRMueso0t6OYir68GCJdYLGbVPY',
    appId: '1:971977021027:web:16c142b2018a2a3ae30a56',
    messagingSenderId: '971977021027',
    projectId: 'tech-runbit-denta',
    authDomain: 'tech-runbit-denta.firebaseapp.com',
    storageBucket: 'tech-runbit-denta.firebasestorage.app',
    measurementId: 'G-L45TXYCL6T',
  );
}
