// File generated by FlutterFire CLI.
//
// Location note: the FlutterFire CLI writes to lib/firebase_options.dart by
// default. This project keeps it alongside the other notification code, so
// re-run configure with the matching --out flag to refresh it:
//
//   flutterfire configure --project=tech-runbit-denta \
//       --out=lib/core/services/notifications/firebase_options.dart
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXQjsxHRMueso0t6OYir68GCJdYLGbVPY',
    appId: '1:971977021027:web:d3e578784011292ce30a56',
    messagingSenderId: '971977021027',
    projectId: 'tech-runbit-denta',
    authDomain: 'tech-runbit-denta.firebaseapp.com',
    storageBucket: 'tech-runbit-denta.firebasestorage.app',
    measurementId: 'G-ZYVX1NCHQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVbSuwXy0Twc0soziJQduzEjgd6QBirKM',
    appId: '1:868915508603:android:82683cb9b467ff3b48f9de',
    messagingSenderId: '868915508603',
    projectId: 'denta-app-60cc0',
    storageBucket: 'denta-app-60cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmjPc1J-ltIIplpWNs3pUSxxiuqbl14ko',
    appId: '1:868915508603:ios:27a52479c420a07148f9de',
    messagingSenderId: '868915508603',
    projectId: 'denta-app-60cc0',
    storageBucket: 'denta-app-60cc0.firebasestorage.app',
    iosBundleId: 'tech.runbit.dentas',
  );

  // No separate macOS app is registered in denta-app-60cc0, so this mirrors
  // the iOS registration — the same arrangement the previous generated file
  // had. If macOS is ever shipped, register it in Firebase and regenerate.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmjPc1J-ltIIplpWNs3pUSxxiuqbl14ko',
    appId: '1:868915508603:ios:27a52479c420a07148f9de',
    messagingSenderId: '868915508603',
    projectId: 'denta-app-60cc0',
    storageBucket: 'denta-app-60cc0.firebasestorage.app',
    iosBundleId: 'tech.runbit.dentas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXQjsxHRMueso0t6OYir68GCJdYLGbVPY',
    appId: '1:971977021027:web:16c142b2018a2a3ae30a56',
    messagingSenderId: '971977021027',
    projectId: 'tech-runbit-denta',
    authDomain: 'tech-runbit-denta.firebaseapp.com',
    storageBucket: 'tech-runbit-denta.firebasestorage.app',
    measurementId: 'G-L45TXYCL6T',
  );
}
